### ISSUE TITLE
[OAS 3.0]Support for scheme for type http in Security

### ISSUE THREAD

**Issue by lagonnebula** [ErikWittern/swagger-snippet#22]
In the components.securitySchemes in OAS3.0 there is a new key "scheme" that can be "bearer" or "basic" for example as described here : [securitySchemeObject](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md#securitySchemeObject)
This new key isn't supported if you specify the auth with 

```YAML
security: 
    - securityName: []
component:
    securitySchemes:
        securityName:
            type: http
            scheme: bearer
```
